name: V2ex Checkin

on:
  # push:
  #   branches:
  #     - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CONFIG: ${{ secrets.CONFIG }}
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}

    steps:
      - uses: actions/checkout@v3
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Echo current time
        run: timedatectl
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check-in
        run: python ./v2ex_checkin.py
